LANG = {
    "en": {
        "start": "Welcome! Choose an option:",
        "coinflip": "Coinflip",
        "d6": "Roll D6",
        "magicball": "Ask Magic Ball",
        "coin_text": "It\'s",
        "heads": "Heads",
        "tails": "Tails",
        "dice": "You rolled a:",
        "magicball_text": "Magicball says: ",
        "help": "/start — Launches the bot and sends a welcome message.\n/help — Shows available commands and what the bot can do.\n/coin — Flips a coin and returns a random result: heads or tails.\n/dice — Rolls a 6 sided dice.\n/magicball — Prints a random Magic 8 Ball response.\n/cat — Sends a random cat photo.\n/dog — Sends a random dog photo.\n/lang — Choice of user language.\n/stylize — Redaction of your image.",
        "flipping_coin": "Flipping coin...",
        "rolling_dice": "Rolling dice...",
        "asking_magicball": "Asking Magicball...",
        "getting_cat": "Fetching a cat...",
        "getting_dog": "Fetching a dog...",
        "getting_language": "Fetching language options...",
        "getting_stylize": "Fetching stylizing options...",
        "responses": [
            "It is certain.",
            "It is decidedly so.",
            "Without a doubt.",
            "Yes – definitely.",
            "You may rely on it.",
            "As I see it, yes.",
            "Most likely.",
            "Outlook good.",
            "Yes.",
            "Signs point to yes.",
            "Reply hazy, try again.",
            "Ask again later.",
            "Better not tell you now.",
            "Cannot predict now.",
            "Concentrate and ask again.",
            "Don't count on it.",
            "My reply is no.",
            "My sources say no.",
            "Outlook not so good.",
            "Very doubtful."
        ],
        "cat_not_found": "Cat not found 😿",
        "dog_not_found": "Dog not found 😢",
        "send_image": "Send me an image to redact",
        "color": "🎨 Color",
        "rotate": "📐 Rotate",
        "filter": "🌀 Filters",
        "cancel": "❌ Cancel",
        "redaction_cancel": "Redaction canceled.",
        "b_and_w": "Black&White",
        "invert": "Invert",
        "return": "← Return",
        "color_effects": "Color effects:",
        "r_cc_90": "90 degrees counter clockwise",
        "r_c_90": "90 degrees clockwise",
        "r_180": "180 degrees",
        "rotate_options": "Rotation options:",
        "blur": "Blur",
        "contour": "Contour",
        "detail": "Detail",
        "edge_enchance": "Edge enchance",
        "emboss": "Emboss",
        "find_edges": "Find edges",
        "filter_effects": "Filter effects:",
        "choose_action_image": "Choose the action to perform on the image",
        "redacted_image": "Here is your redacted image",
    },
    "ru": {
        "start": "Добро пожаловать! Выберите опцию:",
        "coinflip": "Монетка",
        "d6": "Шестигранник",
        "magicball": "Магический Шар",
        "coin_text": "Выпал",
        "heads": "Орел",
        "tails": "Решка",
        "dice": "Выпало:",
        "magicball_text": "Магический шар говорит: ",
        "help": "/start — Запускает бота и отправляет приветственное сообщение.\n/help — Показывает доступные команды и возможности бота.\n/coin — Подбрасывает монету и возвращает случайный результат: орёл или решка.\n/dice — Бросает шестигранный кубик.\n/magicball — Показывает случайный ответ из шара предсказаний.\n/cat — Отправляет случайную фотографию кота.\n/dog — Отправляет случайную фотографию собаки.\n/lang — Выбор языка пользователя.\n/stylize — Обработка вашего изображения.",
        "flipping_coin": "Подбрасываю монетку...",
        "rolling_dice": "Бросаю кубик...",
        "asking_magicball": "Спрашиваю магический шар...",
        "getting_cat": "Получение кота...",
        "getting_dog": "Получение собаки...",
        "getting_language": "Получение языковых опций...",
        "getting_stylize": "Получение параметров стилизации...",
        "responses": [
            "Это несомненно.",
            "Безусловно, так.",
            "Без сомнения.",
            "Да – определённо.",
            "Можешь на это положиться.",
            "Как я вижу, да.",
            "Скорее всего.",
            "Перспективы хорошие.",
            "Да.",
            "Знаки указывают на да.",
            "Ответ неясен, попробуй снова.",
            "Спроси позже.",
            "Лучше не говорить тебе сейчас.",
            "Сейчас предсказать невозможно.",
            "Сосредоточься и спроси снова.",
            "Не рассчитывай на это.",
            "Мой ответ — нет.",
            "Мои источники говорят нет.",
            "Перспективы не очень хорошие.",
            "Очень сомнительно."
        ],
        "cat_not_found": "Кот не найден 😿",
        "dog_not_found": "Бобак не найден 😢",
        "send_image": "Отправь мне изображение для обработки",
        "color": "🎨 Цвет",
        "rotate": "📐 Повернуть",
        "filters": "🌀 Фильтры",
        "cancel": "❌ Отмена",
        "redaction_cancel": "Редактирование отменено.",
        "b_and_w": "Чёрно-белое",
        "invert": "Инвертировать",
        "return": "← Назад",
        "color_effects": "Цветовые эффекты:",
        "r_cc_90": "Повернуть на 90° против часовой",
        "r_c_90": "Повернуть на 90° по часовой",
        "r_180": "Повернуть на 180°",
        "rotate_options": "Параметры поворота:",
        "blur": "Размытие",
        "contour": "Контур",
        "detail": "Детализация",
        "edge_enchance": "Усиление границ",
        "emboss": "Тиснение",
        "find_edges": "Обнаружить края",
        "filter_effects": "Фильтры:",
        "choose_action_image": "Выберите действие для изображения",
        "redacted_image": "Вот ваше обработанное изображение",
    },
    "pl": {
        "start": "Witaj! Wybierz opcję:",
        "coinflip": "Rzut monetą",
        "d6": "Rzuć D6",
        "magicball": "Zadaj pytanie Magicznej Kuli",
        "coin_text": "To jest",
        "heads": "Orzeł",
        "tails": "Reszka",
        "dice": "Wyrzuciłeś:",
        "magicball_text": "Magiczna Kula mówi: ",
        "help": "/start — Uruchamia bota i wysyła wiadomość powitalną.\n/help — Pokazuje dostępne komendy i możliwości bota.\n/coin — Rzuca monetą i zwraca losowy wynik: orzeł lub reszka.\n/dice — Rzuca sześciościenną kostką.\n/magicball — Pokazuje losową odpowiedź Magicznej Kuli.\n/cat — Wysyła losowe zdjęcie kota.\n/dog — Wysyła losowe zdjęcie psa.\n/lang — Wybór języka użytkownika.\n/stylize — Stylizacja twojego obrazu.",
        "flipping_coin": "Rzucanie monetą...",
        "rolling_dice": "Rzucanie kostką...",
        "asking_magicball": "Pytanie Magicznej Kuli...",
        "getting_cat": "Pobieranie kota...",
        "getting_dog": "Pobieranie psa...",
        "getting_language": "Pobieranie opcji językowych...",
        "getting_stylize": "Pobieranie opcji stylizacji...",
        "responses": [
            "To pewne.",
            "Zdecydowanie tak.",
            "Bez wątpienia.",
            "Tak – zdecydowanie.",
            "Możesz na to liczyć.",
            "Jak widzę, tak.",
            "Najprawdopodobniej.",
            "Perspektywy są dobre.",
            "Tak.",
            "Znaki wskazują na tak.",
            "Odpowiedź niejasna, spróbuj ponownie.",
            "Zapytaj ponownie później.",
            "Lepiej ci tego teraz nie mówić.",
            "Nie można teraz przewidzieć.",
            "Skoncentruj się i zapytaj ponownie.",
            "Nie licz na to.",
            "Moja odpowiedź brzmi: nie.",
            "Moje źródła mówią: nie.",
            "Perspektywy niezbyt dobre.",
            "Bardzo wątpliwe."
        ],
        "cat_not_found": "Nie znaleziono kota 😿",
        "dog_not_found": "Nie znaleziono psa 😢",
        "send_image": "Wyślij mi obraz do edycji",
        "color": "🎨 Kolor",
        "rotate": "📐 Obróć",
        "filters": "🌀 Filtry",
        "cancel": "❌ Anuluj",
        "redaction_cancel": "Edycja została anulowana.",
        "b_and_w": "Czarno-białe",
        "invert": "Odwróć kolory",
        "return": "← Powrót",
        "color_effects": "Efekty kolorów:",
        "r_cc_90": "90 stopni przeciwnie do ruchu wskazówek",
        "r_c_90": "90 stopni zgodnie z ruchem wskazówek",
        "r_180": "180 stopni",
        "rotate_options": "Opcje obrotu:",
        "blur": "Rozmycie",
        "contour": "Kontur",
        "detail": "Szczegóły",
        "edge_enchance": "Wzmocnienie krawędzi",
        "emboss": "Tłoczenie",
        "find_edges": "Znajdź krawędzie",
        "filter_effects": "Efekty filtrów:",
        "choose_action_image": "Wybierz akcję do wykonania na obrazie",
        "redacted_image": "Oto twój przetworzony obraz",
    }
}


def get_text(lang, key):
    return LANG.get(lang, LANG["en"]).get(key, "language error")
