LANG = {
    "en": {
        "start": "Welcome! Choose an option:",
        "coinflip": "Coinflip",
        "d6": "Roll D6",
        "magicball": "Ask Magic Ball",
        "coin_text": "It\'s",
        "heads": "Heads",
        "tails": "Tails",
        "dice": "You rolled a:",
        "magicball_text": "Magicball says: ",
        "help": "Type /coin /dice /magicball",
        "flipping_coin": "Flipping coin...",
        "rolling_dice": "Rolling dice...",
        "asking_magicball": "Asking Magicball...",
        "responses": [
            "It is certain.",
            "It is decidedly so.",
            "Without a doubt.",
            "Yes – definitely.",
            "You may rely on it.",
            "As I see it, yes.",
            "Most likely.",
            "Outlook good.",
            "Yes.",
            "Signs point to yes.",
            "Reply hazy, try again.",
            "Ask again later.",
            "Better not tell you now.",
            "Cannot predict now.",
            "Concentrate and ask again.",
            "Don't count on it.",
            "My reply is no.",
            "My sources say no.",
            "Outlook not so good.",
            "Very doubtful."
        ],
        "cat_not_found": "Cat not found 😿",
        "dog_not_found": "Dog not found 😢",
    },
    "ru": {
        "start": "Добро пожаловать! Выберите опцию:",
        "coinflip": "Монетка",
        "d6": "Шестигранник",
        "magicball": "Магический Шар",
        "coin_text": "Выпал",
        "heads": "Орел",
        "tails": "Решка",
        "dice": "Выпало:",
        "magicball_text": "Магический шар говорит: ",
        "help": "Напечатайте /coin /dice /magicball",
        "flipping_coin": "Подбрасываю монетку...",
        "rolling_dice": "Бросаю кубик...",
        "asking_magicball": "Спрашиваю магический шар...",
        "responses": [
            "Это несомненно.",
            "Безусловно, так.",
            "Без сомнения.",
            "Да – определённо.",
            "Можешь на это положиться.",
            "Как я вижу, да.",
            "Скорее всего.",
            "Перспективы хорошие.",
            "Да.",
            "Знаки указывают на да.",
            "Ответ неясен, попробуй снова.",
            "Спроси позже.",
            "Лучше не говорить тебе сейчас.",
            "Сейчас предсказать невозможно.",
            "Сосредоточься и спроси снова.",
            "Не рассчитывай на это.",
            "Мой ответ — нет.",
            "Мои источники говорят нет.",
            "Перспективы не очень хорошие.",
            "Очень сомнительно."
        ],
        "cat_not_found": "Кот не найден 😿",
        "dog_not_found": "Бобак не найден 😢",

    },
    "pl": {
        "start": "Witaj! Wybierz opcję:",
        "coinflip": "Rzut monetą",
        "d6": "Rzuć D6",
        "magicball": "Zadaj pytanie Magicznej Kuli",
        "coin_text": "To jest",
        "heads": "Orzeł",
        "tails": "Reszka",
        "dice": "Wyrzuciłeś:",
        "magicball_text": "Magiczna Kula mówi: ",
        "help": "Wpisz /coin /dice /magicball",
        "flipping_coin": "Rzucanie monetą...",
        "rolling_dice": "Rzucanie kostką...",
        "asking_magicball": "Pytanie Magicznej Kuli...",
        "responses": [
            "To pewne.",
            "Zdecydowanie tak.",
            "Bez wątpienia.",
            "Tak – zdecydowanie.",
            "Możesz na to liczyć.",
            "Jak widzę, tak.",
            "Najprawdopodobniej.",
            "Perspektywy są dobre.",
            "Tak.",
            "Znaki wskazują na tak.",
            "Odpowiedź niejasna, spróbuj ponownie.",
            "Zapytaj ponownie później.",
            "Lepiej ci tego teraz nie mówić.",
            "Nie można teraz przewidzieć.",
            "Skoncentruj się i zapytaj ponownie.",
            "Nie licz na to.",
            "Moja odpowiedź brzmi: nie.",
            "Moje źródła mówią: nie.",
            "Perspektywy niezbyt dobre.",
            "Bardzo wątpliwe."
        ],
        "cat_not_found": "Nie znaleziono kota 😿",
        "dog_not_found": "Nie znaleziono psa 😢",
    }
}


def get_text(lang, key):
    return LANG.get(lang, LANG["en"]).get(key, "language error")
